<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

/**
 * A single piece of feedback submitted by a respondent through a Space's public form.
 *
 * The §15 visibility rule:
 *   is_public = consent_given AND is_wall_of_love AND NOT is_hidden AND NOT soft_deleted.
 *
 * On MySQL this is also enforced as a STORED generated column (see migration).
 * scopePubliclyVisible() is the app-facing API and works on every driver.
 *
 * @property int $id
 * @property int $space_id
 * @property string $name
 * @property string $email
 * @property string $testimonial
 * @property int|null $rating
 * @property bool $consent_given
 * @property bool $is_favorite
 * @property bool $is_wall_of_love
 * @property bool $is_hidden
 * @property bool $is_public
 * @property Carbon $submitted_at
 * @property Carbon|null $created_at
 * @property Carbon|null $updated_at
 * @property Carbon|null $deleted_at
 */
class Testimonial extends Model
{
    /** @use HasFactory<\Database\Factories\TestimonialFactory> */
    use HasFactory, SoftDeletes;

    protected $fillable = [
        'space_id',
        'name',
        'email',
        'testimonial',
        'rating',
        'consent_given',
        'is_favorite',
        'is_wall_of_love',
        'is_hidden',
        'submitted_at',
    ];

    protected $casts = [
        'rating' => 'integer',
        'consent_given' => 'boolean',
        'is_favorite' => 'boolean',
        'is_wall_of_love' => 'boolean',
        'is_hidden' => 'boolean',
        'is_public' => 'boolean',
        'submitted_at' => 'datetime',
    ];

    public function space(): BelongsTo
    {
        return $this->belongsTo(Space::class);
    }

    public function values(): HasMany
    {
        return $this->hasMany(TestimonialValue::class);
    }

    /**
     * Embed-read scope. Resolves to `where('is_public', true)`.
     * Sorted index-ordered off idx_public: no filesort.
     *
     * Caller passes the (already bounded) item_limit; this scope does not paginate.
     *
     * The application rule is restated here as a safety net: even on MySQL, if
     * the STORED expression were ever bypassed (e.g., row-level writes that
     * touch the underlying flags without our saving hook, like raw soft-delete
     * statements), this scope still returns the truth.
     */
    public function scopePubliclyVisible(Builder $query): Builder
    {
        return $query
            ->where('consent_given', true)
            ->where('is_wall_of_love', true)
            ->where('is_hidden', false)
            ->whereNull('deleted_at')
            ->orderByDesc('is_favorite')
            ->orderByDesc('submitted_at');
    }

    /**
     * Live aggregates (limit counts, dashboard). Excludes soft-deleted.
     */
    public function scopeLive(Builder $query): Builder
    {
        return $query->whereNull('deleted_at');
    }

    /**
     * §15 visibility rule.
     * On MySQL the column is STORED-generated by the schema; on SQLite and any
     * other driver we compute it in PHP so the field stays truthful.
     *
     * Note: this is only best-effort. SoftDeletes::delete() uses saveQuietly(),
     * so is_public is not refreshed on soft delete. scopePubliclyVisible()
     * re-evaluates the rule at read time and is the source of truth for reads.
     */
    public function computeIsPublic(): bool
    {
        return $this->consent_given
            && $this->is_wall_of_love
            && ! $this->is_hidden
            && $this->deleted_at === null;
    }

    protected static function booted(): void
    {
        static::saving(function (Testimonial $testimonial): void {
            // Skip on MySQL — the DB sets it from the STORED expression.
            if (DB::connection()->getDriverName() === 'mysql') {
                return;
            }

            $testimonial->is_public = $testimonial->computeIsPublic();
        });
    }
}